#include <stdio.h>
#include <string.h>
#include <stdbool.h>

// These files are generated by `gdbus-codegen`
// Run `cmake . && make` to generate them.
#include "mpris-object.h"
#include "mpris-player.h"

#include "mpris.h"

GVariant* new_metadata_dict_string(const char* key, const char* value) {
    return g_variant_new_dict_entry(
        g_variant_new_string(key),
        g_variant_new_variant(g_variant_new_string(value))
    );
}

GVariant* new_metadata_dict_int64(const char* key, int64_t value) {
    return g_variant_new_dict_entry(
        g_variant_new_string(key),
        g_variant_new_variant(g_variant_new_int64(value))
    );
}

void diplay_track_info(Player* player, XmmsTrackInfo* info) {
    GVariant* entries[7];
    int length = 0;

    entries[length++] = new_metadata_dict_string("mpris:trackid", "/org/mpris/MediaPlayer2/CurrentTrack");

    if (info->title && strlen(info->title)) {
        entries[length++] = new_metadata_dict_string("xesam:title", info->title);
    } else {
        entries[length++] = new_metadata_dict_string("xesam:title", "Unknown Track");
    }

    if (info->artist && strlen(info->artist)) {
        entries[length++] = new_metadata_dict_string("xesam:artist", info->artist);
    }

    if (info->album && strlen(info->album)) {
        entries[length++] = new_metadata_dict_string("xesam:album", info->album);
    }

    if (info->url && strlen(info->url)) {
        entries[length++] = new_metadata_dict_string("xesam:url", info->url);
    }

    entries[length++] = new_metadata_dict_int64("mpris:length", info->duration);

    GVariant* dict = g_variant_new_array(G_VARIANT_TYPE("{sv}"), entries, length);
    mpris_media_player2_player_set_metadata((MprisMediaPlayer2Player*) player, dict);

    mpris_media_player2_player_set_playback_status((MprisMediaPlayer2Player*) player, info->status);
}

GDBusConnection* get_dbus_connection() {
    GError* error = NULL;
    GDBusConnection* bus = g_bus_get_sync(G_BUS_TYPE_SESSION, NULL, &error);

    if (!bus) {
        fprintf(stderr, "%s\n", error->message);
        g_error_free(error);
    } else {
        // Register this program as the mpris handler.
        g_bus_own_name_on_connection(
            bus, "org.mpris.MediaPlayer2.xmms2",
            0, NULL, NULL, NULL, NULL
        );
    }

    return bus;
}

MainObject* init_main_dbus_object(GDBusConnection* bus) {
    // Set up the main media player object.
    MprisMediaPlayer2* main_object = mpris_media_player2_skeleton_new();

    // See the properties in mpris2.xml.
    mpris_media_player2_set_can_quit(main_object, false);
    mpris_media_player2_set_can_raise(main_object, false);
    mpris_media_player2_set_has_track_list(main_object, false);
    mpris_media_player2_set_identity(main_object, "XMMS2");
    mpris_media_player2_set_desktop_entry(main_object, "xmms2");

    // TODO(later) Implement the quit method.
    // TODO(later) Implement the raise method with lxmusic?

    GError* error = NULL;

    if (!g_dbus_interface_skeleton_export(
        (GDBusInterfaceSkeleton*) main_object,
        bus,
        "/org/mpris/MediaPlayer2",
        &error
    )) {
        fprintf(stderr, "%s\n", error->message);
        g_error_free(error);
        g_object_unref(main_object);

        main_object = NULL;
    }

    return (MainObject*) main_object;
}

Player* init_player_dbus_object(GDBusConnection* bus) {
    MprisMediaPlayer2Player* player = mpris_media_player2_player_skeleton_new();

    mpris_media_player2_player_set_playback_status(player, "Stopped");
    mpris_media_player2_player_set_rate(player, 0);
    mpris_media_player2_player_set_volume(player, 0);
    // The position uses the time in microseconds.
    mpris_media_player2_player_set_position(player, 0);
    mpris_media_player2_player_set_minimum_rate(player, 0);
    mpris_media_player2_player_set_maximum_rate(player, 0);
    mpris_media_player2_player_set_can_go_next(player, false);
    mpris_media_player2_player_set_can_go_previous(player, false);
    mpris_media_player2_player_set_can_play(player, false);
    mpris_media_player2_player_set_can_pause(player, false);
    mpris_media_player2_player_set_can_seek(player, false);
    mpris_media_player2_player_set_can_control(player, false);

    // TODO(later) Implement the next method.
    // TODO(later) Implement the previous method.
    // TODO(later) Implement the pause method.
    // TODO(later) Implement the playpause method.
    // TODO(later) Implement the stop method.
    // TODO(later) Implement the play method.
    // TODO(later) Implement the seek method.
    // TODO(later) Implement the setposition method.
    // TODO(later) Implement the openuri method.

    GError* error = NULL;

    if (!g_dbus_interface_skeleton_export(
        (GDBusInterfaceSkeleton*) player,
        bus,
        "/org/mpris/MediaPlayer2",
        &error
    )) {
        fprintf(stderr, "%s\n", error->message);
        g_error_free(error);
        g_object_unref(player);

        player = NULL;
    }

    return (Player*) player;
}
